# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutMenu(object):
    def setupUi(self, AboutMenu):
        AboutMenu.setObjectName("AboutMenu")
        AboutMenu.resize(285, 101)
        self.label = QtWidgets.QLabel(parent=AboutMenu)
        self.label.setGeometry(QtCore.QRect(10, 10, 261, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")

        self.retranslateUi(AboutMenu)
        QtCore.QMetaObject.connectSlotsByName(AboutMenu)

    def retranslateUi(self, AboutMenu):
        _translate = QtCore.QCoreApplication.translate
        AboutMenu.setWindowTitle(_translate("AboutMenu", "About"))
        self.label.setText(_translate("AboutMenu", "<html><head/><body><p>Made with ♥ by ThePi</p><p>1.4.0-alpha</p><p><a href=\"https://github.com/ThePi1/poe-gem-arbitrage\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/ThePi1/poe-gem-arbitrage</span></a></p></body></html>"))
